### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by panghy** [wavefrontHQ/wavefront-dropwizard-metrics-sdk-java#11]
On Dropwizard services, JVM metrics are automatically included and adding them again will cause an exception. We should just catch the IAE and ignore.

```
java.lang.IllegalArgumentException: A metric named jvm.buffers.direct.count already exists
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:91)
	at com.codahale.metrics.MetricRegistry.registerAll(MetricRegistry.java:495)
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:85)
	at com.wavefront.integrations.metrics.WavefrontReporter.<init>(WavefrontReporter.java:394)
	at com.wavefront.integrations.metrics.WavefrontReporter.<init>(WavefrontReporter.java:413)
	at com.wavefront.integrations.metrics.WavefrontReporter.<init>(WavefrontReporter.java:50)
	at com.wavefront.integrations.metrics.WavefrontReporter$Builder.build(WavefrontReporter.java:328)
```

**Comment by hanwavefront** [comment]
https://github.com/wavefrontHQ/wavefront-dropwizard-metrics/pull/14
